;------------------------------------------------------------------------------------------
;	DOT R ALL THE RELEVANT IBIS PREPARTION PROGRAMS
;------------------------------------------------------------------------------------------

.r /home/phk/idl/ibis_lib/pro/ibis_align.pro
.r /home/phk/idl/ibis_lib/pro/ibis_aperture.pro
.r /home/phk/idl/ibis_lib/pro/ibis_calib.pro
.r /home/phk/idl/ibis_lib/pro/ibis_core_map.pro
.r /home/phk/idl/ibis_lib/pro/ibis_create_dstr_struct.pro
.r /home/phk/idl/ibis_lib/pro/ibis_create_struct.pro
.r /home/phk/idl/ibis_lib/pro/ibis_database.pro
.r /home/phk/idl/ibis_lib/pro/ibis_equidistant.pro
.r /home/phk/idl/ibis_lib/pro/ibis_exe.pro
.r /home/phk/idl/ibis_lib/pro/ibis_external.pro
.r /home/phk/idl/ibis_lib/pro/ibis_file_structure.pro
.r /home/phk/idl/ibis_lib/pro/ibis_find_images.pro
.r /home/phk/idl/ibis_lib/pro/ibis_flat_dark_avg_bb.pro
.r /home/phk/idl/ibis_lib/pro/ibis_flat_dark_avg_nb.pro
.r /home/phk/idl/ibis_lib/pro/ibis_gain_nb.pro
.r /home/phk/idl/ibis_lib/pro/ibis_get_aperture.pro
.r /home/phk/idl/ibis_lib/pro/ibis_good_frame_index.pro
.r /home/phk/idl/ibis_lib/pro/ibis_header.pro
.r /home/phk/idl/ibis_lib/pro/ibis_info.pro
.r /home/phk/idl/ibis_lib/pro/ibis_main.pro
.r /home/phk/idl/ibis_lib/pro/ibis_nimages.pro
.r /home/phk/idl/ibis_lib/pro/ibis_prepare.pro
.r /home/phk/idl/ibis_lib/pro/ibis_quick_look.pro
.r /home/phk/idl/ibis_lib/pro/ibis_set.pro
.r /home/phk/idl/ibis_lib/pro/ibis_size.pro
.r /home/phk/idl/ibis_lib/pro/ibis_speckle.pro
.r /home/phk/idl/ibis_lib/pro/ibis_wavelength_shift.pro
.r /home/phk/idl/ibis_lib/pro/ibis_xy_4pnts_corr.pro
.r /home/phk/idl/ibis_lib/access/fits_close.pro
.r /home/phk/idl/ibis_lib/access/fits_open.pro
.r /home/phk/idl/ibis_lib/access/fits_read.pro
.r /home/phk/idl/ibis_lib/access/read_nimages.pro
.r /home/phk/idl/ibis_lib/access/read_size.pro
.r /home/phk/idl/ibis_lib/pol/construct_initial_guess_new.pro
.r /home/phk/idl/ibis_lib/pol/constructtmatrix.pro
.r /home/phk/idl/ibis_lib/pol/constructtmatrix_new.pro
.r /home/phk/idl/ibis_lib/pol/ibis_calib_pol.pro
.r /home/phk/idl/ibis_lib/pol/ibis_calibrate_xt.pro
.r /home/phk/idl/ibis_lib/pol/ibis_demodulate.pro
.r /home/phk/idl/ibis_lib/pol/ibis_demodulate_polcal.pro
.r /home/phk/idl/ibis_lib/pol/ibis_i2quv_mask.pro
.r /home/phk/idl/ibis_lib/pol/ibis_main_polarization.pro
.r /home/phk/idl/ibis_lib/pol/ibis_polcalcurve.pro
.r /home/phk/idl/ibis_lib/pol/ibis_residual.pro
.r /home/phk/idl/ibis_lib/pol/ibis_tmtx.pro
.r /home/phk/idl/ibis_lib/pol/ibis_xmatrix.pro
.r /home/phk/idl/ibis_lib/pol/matrix_inversion.pro
.r /home/phk/idl/ibis_lib/pol/mirror.pro
.r /home/phk/idl/ibis_lib/pol/norm_angle.pro
.r /home/phk/idl/ibis_lib/pol/r_frame_sphtri.pro
.r /home/phk/idl/ibis_lib/pol/retarder.pro
.r /home/phk/idl/ibis_lib/pol/rotat.pro
.r /home/phk/idl/ibis_lib/pol/setmtx.pro
.r /home/phk/idl/ibis_lib/tools/combineshifts.pro
.r /home/phk/idl/ibis_lib/tools/create_aperture.pro
.r /home/phk/idl/ibis_lib/tools/destretch_ibis.pro
.r /home/phk/idl/ibis_lib/tools/detrendshifts.pro
.r /home/phk/idl/ibis_lib/tools/find_ps.pro
.r /home/phk/idl/ibis_lib/tools/get_words.pro
.r /home/phk/idl/ibis_lib/tools/image_displace.pro
.r /home/phk/idl/ibis_lib/tools/kont.pro
.r /home/phk/idl/ibis_lib/tools/lpff_pol.pro
.r /home/phk/idl/ibis_lib/tools/oplot_ibis_aperture.pro
.r /home/phk/idl/ibis_lib/tools/parmin_ibis.pro
.r /home/phk/idl/ibis_lib/tools/pause.pro
.r /home/phk/idl/ibis_lib/tools/reg.pro
.r /home/phk/idl/ibis_lib/tools/scale.pro
;.r /home/phk/idl/ibis_lib/tools/setup_reg.pro
.r /home/phk/idl/ibis_lib/tools/shc.pro
.r /home/phk/idl/ibis_lib/tools/shift_bicub.pro
.r /home/phk/idl/ibis_lib/tools/smoothe.pro
.r /home/phk/idl/ibis_lib/tools/statist.pro
.r /home/phk/idl/ibis_lib/tools/time_conv_new.pro
.r /home/phk/idl/ibis_lib/tools/unique_elements.pro
.r /home/phk/idl/ibis_lib/tools/unshmask.pro
.r /home/phk/idl/ibis_lib/tools/where2.pro
.r /home/phk/idl/ibis_lib/tools/where_n.pro
.r /home/phk/idl/ibis_lib/tools/winplot.pro

;------------------------------------------------------------------------------------------
